name       : shntool
version    : 3.0.10
release    : 1
source     :
    - http://www.etree.org/shnutils/shntool/dist/src/shntool-3.0.10.tar.gz : 74302eac477ca08fb2b42b9f154cc870593aec8beab308676e4373a5e4ca2102
license    : GPL-2.0
component  : multimedia.audio
summary    : a multi-purpose WAVE data processing and reporting utility
description: |
    a multi-purpose WAVE data processing and reporting utility
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
